# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      ./aws/install --install-dir /workspace/aws-cli --bin-dir /workspace/bin
      echo 'export PATH="/workspace/bin:$PATH"' >> ~/.bashrc
      echo 'export PATH="/workspace/bin:$PATH"' >> ~/.zshrc
      source ~/.bashrc
      source ~/.zshrc


